// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
import { Inter, Mulish, Nunito } from 'next/font/google';
import './globals.css'; // Your CSS file path

// Configure the fonts
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // Matches the variable in your layout
});

const mulish = Mulish({
  subsets: ['latin'],
  variable: '--font-mulish',
});

const nunito = Nunito({
  subsets: ['latin'],
  variable: '--font-nunito',
});

export const viewport = {
  colorScheme: 'light', // or 'dark' if your app is dark-themed
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Inject all font variables directly into the body tag */}
      <body className={`${inter.variable} ${mulish.variable} ${nunito.variable} antialiased bg-white`} >
        {children}
      </body>
    </html>
  );
}